### ISSUE TITLE
Additional dependencies not mentioned in the README

### ISSUE THREAD

**Issue by AndreiBarsan** [MarianoJT88/Joint-VO-SF#2]
There seem to be a few dependencies which are required by the build, but not described in the README. Namely, Intel TBB (`apt install libtbb-dev`) and Eigen (personally using a local install autodetected by CMake).

Apart from that, everything seems to work smoothly. Actually, for the "Freiburg3/walk xyz" sequence, using all the default parameters from this repo, I get a mean processing time of ~29ms, over the entire sequence (STD ~5.7ms) which is considerably faster than the 80ms specified in the paper, provided I'm not doing anything wrong. (28.8ms @ 3.4ms std for walk static)

I'm on Ubuntu 16.04, and my CPU is an Intel Core i7-6700k, so good, but nothing too ridiculous.

Edit: I just double checked the paper, and it seems the experiments were run on a laptop Core i7-4712 HQ, so the speedup is not too surprising, but still nice to see!

Keep up the great work!

**Comment by MarianoJT88** [comment]
Hi Andrei, thanks for your positive feedback!

You are right I forgot to mentioned TBB, I will include that in the README file. Regarding Eigen, it is included/embedded by default in MRPT so I thought it was not worth mentioning it (in fact you can see that the CMakeList.txt file does not require Eigen explicitly).

As far as the runtime is concerned, I think you get a correct results. Freiburg3 sequences are typically faster because they contain images with many pixels with null depth (which are not processed). Moreover, I improved the code during the last months so now it is faster than the paper says. Last, I think you have a pretty good CPU :)

Regards,
Mariano

**Comment by AndreiBarsan** [comment]
Awesome, thanks for clearing things up. I didn't know that Eigen came with MRPT, since I'm not that familiar with MRPT, but yeah, that does make sense.
