### ISSUE TITLE
Why MC-flow performance is better than this way ?

### ISSUE THREAD

**Issue by payne11** [MarianoJT88/Joint-VO-SF#9]
I've read your paper"Smooth Piece-Wise Rigid Scene Flow from RGB-D Images.", MC-flow performance is better than this way , but it's slow, and I think that  the different because of layer optimization  ,which is"smooth Piece-Wise Rigid Scene Flow from RGB-D Images" use  Primal-Dual algorithm ,but  this article is based on the optimization of the four energy functions. whether if my understanding is wrong,Can you tell me some details ? ,Thank you !

**Comment by MarianoJT88** [comment]
Dear payne11, your questions are generic/theoretical and does not have to do with the code shared in this repository. For this reason, this is the last question of this kind I answer. From now on I will ignore them.

Motion cooperation flow is more precise because there we optimize for the labels as well, and for this reason it is also much slower (here we only compute the segmentation once with K-Means and keep it fixed after that). I don't know what you mean when you refer to the "four energy functions".
